//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderIngredient
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ExstraIngredientID { get; set; }
        public string Exstra { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<int> RestourantID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> IngredientID { get; set; }
    
        public virtual ExstraIngredient ExstraIngredient { get; set; }
        public virtual Ingredient Ingredient { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual Restourant Restourant { get; set; }
        public virtual Table Table { get; set; }
    }
}
