//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translate
    {
        public int ID { get; set; }
        public Nullable<int> ValueID { get; set; }
        public Nullable<int> LanguageID { get; set; }
        public string Value { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual Value Value1 { get; set; }
    }
}
