//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public int ID { get; set; }
        public string UserType1 { get; set; }
        public Nullable<int> RestourantID { get; set; }
    
        public virtual Restourant Restourant { get; set; }
    }
}
